### ISSUE TITLE
Use .env file for storing bot tokens and other secrets

### ISSUE THREAD

**Issue by TijsDeBelie** [saptarshibasu15/geez#1]
As the title says it's better to use a .env file (Git protects you from uploading those) and the concept is very nice to have.

If you want I can quickly implement this

**Comment by saptarshibasu15** [comment]
> As the title says it's better to use a .env file (Git protects you from uploading those) and the concept is very nice to have.
> 
> If you want I can quickly implement this

Sure please go ahead! ☺
